### ISSUE TITLE
untrusted :3

### ISSUE THREAD

**Issue by trolloos** [DubbleClick/csgo-sdk#1]
Is the clamping done wrong or is the cheat detected? I don't know but I got untrusted from this cheat...

**Comment by henderkes** [comment]
This isn't even meant to be a cheat but mostly published for the sdk. Also this clamps correctly and I sincerely doubt it's detected, so it most definitely wasn't because of this.

**Comment by trolloos** [comment]
https://www.youtube.com/watch?v=dCiHQ20hg8E

Definitly looks like it was this cheat

**Comment by henderkes** [comment]
https://github.com/DubbleClick/csgo-sdk/blob/master/csgo-sdk/Hack/Hooks/CreateMove.cpp#L55
https://github.com/DubbleClick/csgo-sdk/blob/master/csgo-sdk/Hack/Hooks/CreateMove.cpp#L3
https://github.com/DubbleClick/csgo-sdk/blob/master/csgo-sdk/sdk/Classes%20Structs/QAngle.h#L197

Too bad it wasn't.

**Comment by trolloos** [comment]
No problem I never had a problem I already used it for 9 days but it was manual ban I guess rip
